services:
  tugtainer:
    image: quenary/tugtainer:latest
    container_name: ${STACK_NAME_PREFIX}-tugtainer
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Tugtainer
      - homepage.icon=docker.png
      - homepage.href=http://${HOMEPAGE_HOST:-localhost}:${TUGTAINER_WEB_PORT:-80}
      - homepage.description=Docker image updater
    restart: unless-stopped
    ports:
      - "${TUGTAINER_WEB_PORT:-80}:80"
    volumes:
      - tugtainer_data:/tugtainer
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ../../.env.tugtainer

volumes:
  tugtainer_data:
