version: '3.8'

services:
  backend:
    image: infisical/infisical:latest
    container_name: ${STACK_NAME_PREFIX}-infisical
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ../../.env.infisical
    ports:
      - "${INFISICAL_PORT:-8086}:8080"
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Infisical
      - homepage.icon=lock.png
      - homepage.href=https://infisical.${BASE_DOMAIN}
      - homepage.description=Secret management platform
      # Traefik
      - traefik.enable=true
      - traefik.http.routers.infisical.rule=Host(`infisical.${BASE_DOMAIN}`)
      - traefik.http.routers.infisical.entrypoints=websecure
      - traefik.http.routers.infisical.tls.certresolver=cloudflare
      - traefik.http.routers.infisical.service=infisical
      - traefik.http.services.infisical.loadbalancer.server.port=8080
    networks:
      - traefik
      - infisical

  redis:
    image: redis:7-alpine
    container_name: ${STACK_NAME_PREFIX}-infisical-redis
    restart: always
    networks:
      - infisical
    volumes:
      - redis_data:/data

  db:
    image: postgres:14-alpine
    container_name: ${STACK_NAME_PREFIX}-infisical-db
    restart: always
    env_file:
      - ../../.env.infisical
    networks:
      - infisical
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local

networks:
  traefik:
    external: true
  infisical:
    driver: bridge
