version: "3.8"

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    # environment:
    #   - HOSTNAME=https://plex.${HOMELAB_DOMAIN}
    env_file:
      - ../../.env
      - .homelab/.env
    ports:
      - 32400:32400
      - 8324:8324
      - 32469:32469
      - 1900:1900
      - 32410:32410
      - 32412:32412
      - 32413:32413
      - 32414:32414
    volumes:
      - ./.homelab/config:/config
      - ./.homelab/transcode:/transcode
      - /Volumes/Media:/data
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=https://plex.${HOMELAB_DOMAIN}
      - homepage.widget.fields=["streams","movies","tv"]
      - homepage.widget.type=plex
      - homepage.widget.url=https://plex.${HOMELAB_DOMAIN}
      - homepage.widget.key=${PLEX_TOKEN}
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.${HOMELAB_DOMAIN}`)
      - traefik.http.routers.plex.entrypoints=https
      - traefik.http.routers.plex.tls=true
      - traefik.http.services.plex.loadbalancer.server.port=32400
