

services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: ${STACK_NAME_PREFIX}-metube
    env_file:
      - ../../.env
    environment:
      - DEFAULT_THEME=dark
      - PUBLIC_HOST_URL=https://metube.${HOMELAB_DOMAIN}
      - YTDL_OPTIONS={}
    ports:
      - 8085:8081
    volumes:
      - /Volumes/Media/downloads:/downloads
    restart: unless-stopped
      