services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: ${STACK_NAME_PREFIX}-metube
    env_file:
      - ../../.env.metube
    environment:
      - DEFAULT_THEME=dark
      - YTDL_OPTIONS={}
    ports:
      - 8085:8081
    volumes:
      - /Volumes/Media/downloads:/downloads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
