services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${STACK_NAME_PREFIX}-portainer
    env_file:
      - ../../.env.portainer
    labels:
      # Homepage
      - homepage.group=Infrastructure
      - homepage.name=Portainer
      - homepage.icon=portainer.png
      - homepage.href=https://${PORTAINER_SUBDOMAIN:-portainer}.${BASE_DOMAIN}
      - homepage.description=Docker management UI
      # Traefik
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`${PORTAINER_SUBDOMAIN:-portainer}.${BASE_DOMAIN}`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls.certresolver=cloudflare
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    ports:
      - ${PORTAINER_WEB_PORT:-9000}:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true

volumes:
  portainer_data:
