# Services are auto-discovered via Docker labels
# You can also manually define services here
# See: https://gethomepage.dev/configs/services/

- Cron:
    - Vault Daily:
        icon: vault.png
        href: "{{HOMEPAGE_VAR_CRON_STATUS_URL}}/vault-daily.json"
        ping: "{{HOMEPAGE_VAR_CRON_STATUS_INTERNAL_URL}}/vault-daily.json"
        statusStyle: dot
        description: Daily snapshot
    - Vault Weekly:
        icon: vault.png
        href: "{{HOMEPAGE_VAR_CRON_STATUS_URL}}/vault-weekly.json"
        ping: "{{HOMEPAGE_VAR_CRON_STATUS_INTERNAL_URL}}/vault-weekly.json"
        statusStyle: dot
        description: Weekly snapshot
    - Vault Monthly:
        icon: vault.png
        href: "{{HOMEPAGE_VAR_CRON_STATUS_URL}}/vault-monthly.json"
        ping: "{{HOMEPAGE_VAR_CRON_STATUS_INTERNAL_URL}}/vault-monthly.json"
        statusStyle: dot
        description: Monthly snapshot
