---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- DNS:
  - Heimdall:
      icon: pi-hole.png
      href: http://{{HOMEPAGE_VAR_HEIMDALL_IP}}/admin
      widget:
        type: pihole
        url: http://{{HOMEPAGE_VAR_HEIMDALL_IP}}
        key: {{HOMEPAGE_VAR_HEIMDALL_API_KEY}}
        fields: ["queries", "blocked", "blocked_percent"]

  - Thor:
      icon: pi-hole.png
      href: http://{{HOMEPAGE_VAR_THOR_IP}}/admin
      widget:
        type: pihole
        url: http://{{HOMEPAGE_VAR_THOR_IP}}
        key: {{HOMEPAGE_VAR_THOR_API_KEY}}
        fields: ["queries", "blocked", "blocked_percent"]

  - Loki:
      icon: pi-hole.png
      href: http://{{HOMEPAGE_VAR_LOKI_IP}}/admin
      widget:
        type: pihole
        url: http://{{HOMEPAGE_VAR_LOKI_IP}}
        key: {{HOMEPAGE_VAR_LOKI_API_KEY}}
        fields: ["queries", "blocked", "blocked_percent"]
