version: "3.8"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - ../../.env
      - .homelab/.env
    ports:
      - 3000:3000
    volumes:
      - ./.homelab/config:/app/config
      - ./config/bookmarks.yaml:/app/config/bookmarks.yaml:ro
      - ./config/docker.yaml:/app/config/docker.yaml:ro
      - ./config/services.yaml:/app/config/services.yaml:ro
      - ./config/settings.yaml:/app/config/settings.yaml:ro
      - ./config/widgets.yaml:/app/config/widgets.yaml:ro
      # - ./config/custom.css:/app/config/custom.css:ro
      # - ./config/custom.js:/app/config/custom.js:ro
      # - ./config/kubernetes.yaml:/app/config/kubernetes.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${HOMELAB_DOMAIN}`)
      - traefik.http.routers.homepage.entrypoints=https
      - traefik.http.routers.homepage.tls=true
      - traefik.http.services.homepage.loadbalancer.server.port=3000
