

services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    volumes:
      - ../../.homelab/tdarr/configs:/app/configs
      - ../../.homelab/tdarr/logs:/app/logs
      - ../../.homelab/tdarr/server:/app/server
      - ../../.homelab/tdarr/transcode_cache:/temp
      - /Volumes/Media:/media
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode

