services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: ${STACK_NAME_PREFIX}-tdarr
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    volumes:
      - tdarr_configs:/app/configs
      - tdarr_logs:/app/logs
      - tdarr_server:/app/server
      - tdarr_transcode_cache:/temp
      - /Volumes/Media:/media
    restart: unless-stopped
    env_file:
      - ../../.env.tdarr
    environment:
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8265"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  tdarr_configs:
  tdarr_logs:
  tdarr_server:
  tdarr_transcode_cache:

